#!/usr/bin/env bash
# vim:ft=sh:ts=2:sts=2:sw=2:et

set -e

#
# Arguments
#

if [[ -z "${2}" ]]; then
  echo "usage: ${0} <server-name> <client-name>" >&2
  exit 1
fi

#
# Variables
#

script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
server_name="${1}"
server_path="${script_path}/../server/${server_name}"
server_conf="${server_path}/server.conf"
server_full_conf="${script_path}/../${server_name}.conf"
client_name="${2}"
client_path="${server_path}/client/${client_name}"

#
# Sanity check
#

if [[ ! -d "${client_path}" ]]; then
  echo "client ${client_name} does not exist" >&2
  exit 1
fi

#
# Destroy
#

rm -rf "${client_path}"

#
# Regenerate the full server config
#

{
  cat "${server_conf}"
  echo

  while read -r client_conf_part; do
    cat "${client_conf_part}"
    echo
  done < <(
    grep -H 'AllowedIPs *= ' "${server_path}"/client/*/*.server.conf |\
      awk -F'[:=]' '{ print($3, $1) }' |\
      sort -V |\
      awk '{ print($2) }'
  )
} >"${server_full_conf}"
