#!/usr/bin/env bash
# vim:ft=sh:ts=2:sts=2:sw=2:et

set -e

#
# Arguments
#

if [[ -z "${1}" ]]; then
  echo "usage: ${0} <server-name>" >&2
  exit 1
fi

#
# Variables
#

script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
server_name="${1}"
server_path="${script_path}/../server/${server_name}"
server_full_conf="${script_path}/../${server_name}.conf"

#
# Sanity check
#

if [[ ! -d "${server_path}" ]]; then
  echo "server ${server_name} does not exist" >&2
  exit 1
fi

#
# Destroy
#

rm -rf "${server_path}"
rm -f "${server_full_conf}"
